### ISSUE TITLE
Error in demo: FileNotFoundError

### ISSUE THREAD

**Issue by janna00** [oskopek/mvae#5]
Thanks for the package!

When running (Mac Hierra): python -m mt.examples.run --dataset="mnist" --model="h2,s2,e2" --fixed_curvature=False 

I got an error after 100 epochs: FileNotFoundError: [Errno 2] No such file or directory: './chkpt/vae-mnist-e2,h2,s2-2020-06-14T17:45:14.337416/None.chkpt'

Thanks in advance!

**Comment by oskopek** [comment]
Hi Janna,

I was unfortunately unable to reproduce the issue, and I couldn't figure out why that would be happening :/ Could you please tell me your python version (`python --version`) and if you installed all the dependencies as suggested?

Thanks!

**Comment by oskopek** [comment]
Unfortunately I wasn't able to reproduce the behavior. Feel free to re-open if the error still appears.
