### ISSUE TITLE
Pre-trained embeddings for those four datasets

### ISSUE THREAD

**Issue by thupchnsky** [oskopek/mvae#6]
Dear authors,

Thanks for the great code! I am wondering do you also have the pre-trained embeddings of those four datasets included in the repository? Because I want to do some visualization for the embeddings. Seems like they should be in mt/data/, but only find four scripts there. 

Also when I want to use the mt/examples/run.py to generate the embeddings myself, I find that with the following parameters: 
`--dataset="mnist" --model="h2,s2,e2" --fixed_curvature=True --epochs=50 --warmup=10 --lookahead=5 --show_embeddings=10`
only the embeddings of the last epoch 49 will be recorded in chkpt/ folder, instead of recording embeddings every 10 epochs. I looked into the code a little bit, finding that `show_embeddings` is only used in `_test_epoch`, which is only called once in `train_stopping`. Maybe I miss something here, but seems like it will only save the last embeddings. 

Thanks for your help in advance!

**Comment by oskopek** [comment]
Thanks a lot for reporting this!

I'll try to fix the behavior and answer your questions this evening.

Sorry for the delay!

**Comment by oskopek** [comment]
Hi, thanks a lot for using the code! I looked in my data backups, don't have any exported embeddings saved, unfortunately :/

But, I went and implemented the functionality you're looking for. Try running:

```
python -m mt.examples.run --dataset="mnist" --model="h2,s2,e2" --fixed_curvature=True --epochs=50 --warmup=10 --lookahead=5 --show_embeddings=1 --test_every=10 --export_embeddings=1
```

this should run testing every 10 epochs and always export embeddings and show them in tensorboard. You'll find the exported tensors in the model checkpoint directory, subdirectory `repr`. If the tsv files for tensorboard are enough, consider not using the --export_embeddings flag, as it will make things a lot slower. Feel free to improve the code and send a pull request!

Example directory:
```shell
$ tree
.
├── 00002
│   ├── eval%2fcomp_000_h2%2fembeddings
│   │   ├── metadata.tsv
│   │   └── tensors.tsv
│   ├── eval%2fcomp_001_s2%2fembeddings
│   │   ├── metadata.tsv
│   │   └── tensors.tsv
│   ├── eval%2fcomp_002_e2%2fembeddings
│   │   ├── metadata.tsv
│   │   └── tensors.tsv
│   └── eval%2ftotal_embeddings
│       ├── metadata.tsv
│       └── tensors.tsv
├── 0.chkpt
├── 1.chkpt
├── 2.chkpt
├── events.out.tfevents.1612116640.olorin
├── projector_config.pbtxt
└── repr
    ├── eval_comp_000_h2_2.pt
    ├── eval_comp_001_s2_2.pt
    ├── eval_comp_002_e2_2.pt
    ├── eval_labels_2.pt
    └── eval_total_2.pt

6 directories, 18 files
```

Let me know if it works for you!

**Comment by thupchnsky** [comment]
Thanks for the response! I have also found that there are already implemented export functions (although commented) called `_export_representations` in Trainer, so I was using that. 

Just want to leave a small comment here that when using cifar dataset with default parameters, the forwarding process `reparametrized, concat_z, x_mb_ = self.model(x_mb)` in `_export_representations` seems to take too much GPU memory when we try to do all the computing first then export. In this case it always gives me CUDA out of memory error. I was using CPU instead to do the export job, but I think you can also change it to exporting each batch after computing then free the memory?

Anyway thanks for your help! This is a great work.

**Comment by oskopek** [comment]
CPU would work as a workaround, yes. Feel free to send a pull request to
fix the cuda exporting if it blocks you, it shouldn't be a complicated
change.
